// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Task struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Status      int32          `json:"status"`
	Priority    int32          `json:"priority"`
	DueDate     int64          `json:"due_date"`
}

type User struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UserTask struct {
	UserID int32 `json:"user_id"`
	TaskID int32 `json:"task_id"`
}
